name: anna_analysis
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pip
  - pip:
    - inmoose
    - pytest